# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_easiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='take_again',
            field=models.IntegerField(default=0),
        ),
    ]
