# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_easinessvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easinessvote',
            old_name='choice_text',
            new_name='easinessvote_text',
        ),
    ]
